---
name: tests

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: gofmt
        run: test -z $(gofmt -l .)
      - name: test
        run: make test
        env:
          GITHUB_READONLY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: help
        run: go run main.go --help
      - name: parse a test file
        run: make simple
